##################################Inicio#################################

homepage:
  url:   /
  param: { module: ica, action: index }

legal:
  url:   /
  param: { module: ica, action: index }

about:
  url:   /
  param: { module: ica, action: index }

download_manual:
  url:   /download/manual.:sf_format
  param: { module: ica, action: DownloadManual, sf_format: pdf}


icabox:
  url:   /icabox
  param: { module: icabox, action: index }

reparacion:
  url:   /reparacion
  param: { module: reparacion, action: index }

###################################Password(Pendiente)##################

change_password:
  url:              /changepassword
  param:            { module: ica, action: ChangePasswordShow }
change_password_do:
  url:              /dochangepassword
  param:            { module: ica, action: ChangePassword }

recover_password:
  url:              /recoverpassword
  param:            { module: ica, action: RecoverPasswordShow }
recover_password_do:
  url:              /dorecoverpassword
  param:            { module: ica, action: RecoverPassword }

##################################sfGuardPlugin#################################

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

